language: cpp
compiler: g++

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

before_script:
- sudo apt-get install libpthread-stubs0-dev libgl1-mesa-dev libx11-dev
- sudo apt-get install libxrandr-dev libfreetype6-dev libglew1.5-dev
- sudo apt-get install libjpeg8-dev libgpgme11-dev libsndfile1-dev libopenal-dev libjpeg62
- sudo apt-get install libsfml-dev

script: cd build && cmake . && make && ./tests
